# Generated by Django 5.1.3 on 2024-11-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_url_product_product_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/placeholder.jpg', null=True, upload_to='product_images/'),
        ),
    ]
